version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: jansodomka/wea_semestralni_prace:backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    image: jansodomka/wea_semestralni_prace:frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend