version: '3.8'  # Doporučuji použít novější verzi, např. 3.8

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"  # Mapování portu 80 z Nginx na port 3000 hostitelského systému
    depends_on:
      - backend
