"""empty message

Revision ID: 7bab8842ac11
Revises: ae2afb9c2b05
Create Date: 2024-11-09 10:04:26.128111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bab8842ac11'
down_revision = 'ae2afb9c2b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('stock_quantity')
        batch_op.drop_column('publication_date')
        batch_op.drop_column('weight')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('price')
        batch_op.drop_column('publisher')
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('publication_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
