"""empty message

Revision ID: ae2afb9c2b05
Revises: 
Create Date: 2024-11-09 10:03:06.686934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2afb9c2b05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('stock_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('publication_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('weight')
        batch_op.drop_column('publication_date')
        batch_op.drop_column('publisher')
        batch_op.drop_column('language')
        batch_op.drop_column('stock_quantity')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
