"""empty message

Revision ID: d666278b71a6
Revises: 7bab8842ac11
Create Date: 2024-11-09 10:52:48.839025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd666278b71a6'
down_revision = '7bab8842ac11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_isbn', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.ISBN10'], name='favorites_book_isbn_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'book_isbn', name='favorites_pkey')
    )
    # ### end Alembic commands ###
