"""empty message

Revision ID: e0ce420b08d5
Revises: d666278b71a6
Create Date: 2024-11-09 18:24:17.253452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ce420b08d5'
down_revision = 'd666278b71a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_isbn10', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_isbn10'], ['book.ISBN10'], name='user_favorites_book_isbn10_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'book_isbn10', name='user_favorites_pkey')
    )
    # ### end Alembic commands ###
